package resBody;

import org.testng.annotations.Test;

public class Res {
	
	public static String getres1() {
		
		return "{\r\n"
				+ "  \"name\": \"duggar\",\r\n"
				+ "  \"design\": \"manager\",\r\n"
				+ "  \"salary\": 5000\r\n"
				+ "}";
	}

	@Test
	public static String getres2() {
		
		return "{\r\n"
				+ "\"employees\":[\r\n"
				+ "{\r\n"
				+ "\"empName\":\"chris\",\r\n"
				+ "  \"designature\":\"qalead\",\r\n"
				+ "  \"salary\":10000,\r\n"
				+ "  \"phone\":\"5666\" \r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"empName\":\"john\",\r\n"
				+ "  \"designature\":\"manager\",\r\n"
				+ "  \"salary\":80000,\r\n"
				+ "  \"phone\":\"5666654\" \r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"empName\":\"cruise\",\r\n"
				+ "  \"designature\":\"HR\",\r\n"
				+ "  \"salary\":80000,\r\n"
				+ "  \"phone\":\"5666654\" \r\n"
				+ "}  \r\n"
				+ "]\r\n"
				+ "}";
		
	}
	public static String getres3() {
		
		return "{\r\n"
				+ "\"employees\":[\r\n"
				+ "{\r\n"
				+ "\"empName\":\"chris\",\r\n"
				+ "  \"designature\":\"qalead\",\r\n"
				+ "  \"salary\":10000,\r\n"
				+ "  \"phone\":\"565566\",\r\n"
				+ "\r\n"
				+ "  \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"travel\",\r\n"
				+ "    \"reading\"\r\n"
				+ "    ]\r\n"
				+ "},{\r\n"
				+ "\"empName\":\"james\",\r\n"
				+ "  \"designature\":\"test lead\",\r\n"
				+ "  \"salary\":12698,\r\n"
				+ "  \"phone\":\"565566\",\r\n"
				+ "\r\n"
				+ "  \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"football\",\r\n"
				+ "    \"snooker\"\r\n"
				+ "    ]\r\n"
				+ "}\r\n"
				+ " ,{\r\n"
				+ "\"empName\":\"peter\",\r\n"
				+ "  \"designature\":\"test lead\",\r\n"
				+ "  \"salary\":69854,\r\n"
				+ "  \"phone\":\"565566\",\r\n"
				+ "\r\n"
				+ "  \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"swimming\",\r\n"
				+ "    \"chess\"\r\n"
				+ "    ]\r\n"
				+ "}\r\n"
				+ "]\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "";
	}
	
	public static String getres4() {
		return "[\r\n"
				+ "{\r\n"
				+ "\"empName\":\"chris\",\r\n"
				+ "  \"designature\":\"qalead\",\r\n"
				+ "  \"salary\":10000,\r\n"
				+ "  \"phone\":\"565566\",\r\n"
				+ "\r\n"
				+ "  \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"travel\",\r\n"
				+ "    \"reading\"\r\n"
				+ "    ]\r\n"
				+ "},{\r\n"
				+ "\"empName\":\"james\",\r\n"
				+ "  \"designature\":\"test lead\",\r\n"
				+ "  \"salary\":698,\r\n"
				+ "  \"phone\":\"565566\",\r\n"
				+ "\r\n"
				+ "  \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"football\",\r\n"
				+ "    \"snooker\"\r\n"
				+ "    ]\r\n"
				+ "}\r\n"
				+ " \r\n"
				+ "]\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "";
	}
	
	
	
	
	public static String getres4b() {
		return "[\r\n"
				+ "    {\r\n"
				+ "       \r\n"
				+ "        \"name\": \"Bakula Chattopadhyay\",\r\n"
				+ "        \"email\": \"bakula_chattopadhyay@mccullough.test\",\r\n"
				+ "        \"gender\": \"male\",\r\n"
				+ "        \"status\": \"inactive\",\r\n"
				+ "       \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"travel\",\r\n"
				+ "    \"reading\"\r\n"
				+ "    ]\r\n"
				+ "},{\r\n"
				+ "      \r\n"
				+ "        \"name\": \"Kaenon\",\r\n"
				+ "        \"email\": \"kalmenon@schneider-west.test\",\r\n"
				+ "        \"gender\": \"male\",\r\n"
				+ "        \"status\": \"inactive\",\r\n"
				+ "             \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"travel\",\r\n"
				+ "    \"reading\"\r\n"
				+ "    ]\r\n"
				+ "},{\r\n"
				+ "    }\r\n"
				+ ",\r\n"
				+ "    {\r\n"
				+ "        \"name\": \"Ad Sinha\",\r\n"
				+ "        \"email\": \"ad_sinha@goodwin.test\",\r\n"
				+ "        \"gender\": \"female\",\r\n"
				+ "        \"status\": \"inactive\",\r\n"
				+ "             \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"cooking\",\r\n"
				+ "    \"reading\"\r\n"
				+ "    ]\r\n"
				+ "},{\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"name\": \"Ganaaik\",\r\n"
				+ "        \"email\": \"ganakulgowski.example\",\r\n"
				+ "        \"gender\": \"male\",\r\n"
				+ "        \"status\": \"inactive\",\r\n"
				+ "             \"hobbies\":\r\n"
				+ "  [\r\n"
				+ "\r\n"
				+ "    \"travel\",\r\n"
				+ "    \"fishing\"\r\n"
				+ "    ]\r\n"
				+ "},{\r\n"
				+ "    }\r\n"
				+ "]";
	}
}
